name: believersHub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  lottie: ^3.3.2
  flutter_svg: ^2.2.2
  page_transition: ^2.2.1
  http: ^1.6.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.1
  google_fonts: ^6.3.2
  rename_app: ^1.6.5
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2

  # Google
  google_sign_in: ^6.2.1

  # Facebook
  flutter_facebook_auth: ^7.0.0

  # Apple
  sign_in_with_apple: ^6.0.0
  dio: ^5.9.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/images/
  - assets/png/  
  - assets/fonts/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    